apiVersion: v1
kind: Service
metadata:
  name: conversational-commerce-agent-backend
  labels:
    app: conversational-commerce-agent-backend
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: conversational-commerce-agent-backend
