apiVersion: v1
kind: Service
metadata:
  name: conversational-commerce-agent-frontend
  labels:
    app: conversational-commerce-agent-frontend
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: conversational-commerce-agent-frontend
